### ISSUE TITLE
Plex Filename Sanitization can cause "OSError: [Errno 36] File name too long" on long video names.

### ISSUE THREAD

**Issue by Slothstronaut** [jmbannon/ytdl-sub#1092]
Current config is using the out-of-the-box "Plex TV Show Collection" preset without any other tweaks. 

Trying to download Youtube videos with exceptionally long titles is causing the "OSError: [Errno 36] File name too long" error and crashing the program.

An example video that causes it: https://www.youtube.com/watch?v=qcY39pi3f40

The relevant error log is attached.
[2024-10-08-231129.uchikubi-gokumon.error.log](https://github.com/user-attachments/files/17309431/2024-10-08-231129.uchikubi-gokumon.error.log)

I have a handful of other videos that this does it on as well. I tried passing the "trim-filenames" parameter to yt-dlp but it didn't help.

**Comment by jmbannon** [comment]
Create a config file and set this: https://ytdl-sub.readthedocs.io/en/latest/config_reference/config_yaml.html#ytdl_sub.config.config_validator.ConfigOptions.file_name_max_bytes

```
configuration:
  file_name_max_bytes: 200
```

**Comment by xlyralycanx** [comment]
Didn't wanna take up another issue for this - I came across the same issue, fixed by modifying max_bytes, just wanted to add that both OP's and my errors were thrown by the video temp files appended with '-ytdl-sub-incomplete', and both names totaled 256 bytes, not 255. Obviously this is a rare occurrence and not worth changing aha

**Comment by jmbannon** [comment]
Seems like a worthy reason to re-open

**Comment by jmbannon** [comment]
Closing, should be fixed from the linked PR
