### ISSUE TITLE
Plex preset tweaks

### ISSUE THREAD

**Issue by henryb3** [jmbannon/ytdl-sub#281]
The Plex preset is working great.   I do have a few suggestions to make it a little cleaner for Plex users:

```
      episode_title: "{title}"
      episode_file_name: "{tv_show_name_sanitized} - s{season_number_padded}e{episode_number_padded} - {title}"
```
I removed the uid references as well as the "." between the season and episode.  I also added the TV show name as per Plex's naming recommendations.

**Comment by jmbannon** [comment]
Thanks for the suggestion @henryb3 

The reason I keep the file name short is because it's easy to hit the OS file name max size limit (as seen in another GH issue). From my experience, plex still imported the file name correctly with the `.` and uid.

As for the episode title - it's encouraged to customize! Glad you were able to figure it out
