### ISSUE TITLE
Downloads keep failing

### ISSUE THREAD

**Issue by leshokunin** [jmbannon/ytdl-sub#693]
I'm using the docker image with my own cookie. I keep getting 403s. Nothing changed from when it used to work.

![image](https://github.com/jmbannon/ytdl-sub/assets/30949000/0f08ebc0-3b2a-41c4-a84b-1ee01582b888)

![image](https://github.com/jmbannon/ytdl-sub/assets/30949000/c09c8fb8-f8fc-4a72-96fb-f48c94facfc1)

Any ideas?

**Comment by jmbannon** [comment]
This is more-so a yt-dlp issue. 403 typically means you've been explicitly rejected, which may imply a hard-ban from YouTube. Make sure you're on the latest version and maybe make a new account with a new cookie file (or no cookie at all). Worst-case you may need to download via VPN.

Going to close since this isn't ytdl-sub related, but happy to continue helping

**Comment by leshokunin** [comment]
Thanks! I'll try to reduce my crontabs frequency and remove the cookies to see what happens.
